# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/veritaris/Documents/Study/Programming/С/gengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/veritaris/Documents/Study/Programming/С/gengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/veritaris/Documents/Study/Programming/С/gengine/CMakeFiles /Users/veritaris/Documents/Study/Programming/С/gengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/veritaris/Documents/Study/Programming/С/gengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c-client

# Build rule for target.
c-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c-client
.PHONY : c-client

# fast build rule for target.
c-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-client.dir/build.make CMakeFiles/c-client.dir/build
.PHONY : c-client/fast

#=============================================================================
# Target rules for targets named c-server

# Build rule for target.
c-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c-server
.PHONY : c-server

# fast build rule for target.
c-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-server.dir/build.make CMakeFiles/c-server.dir/build
.PHONY : c-server/fast

#=============================================================================
# Target rules for targets named array_list

# Build rule for target.
array_list: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 array_list
.PHONY : array_list

# fast build rule for target.
array_list/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/array_list.dir/build.make CMakeFiles/array_list.dir/build
.PHONY : array_list/fast

#=============================================================================
# Target rules for targets named gengine-client

# Build rule for target.
gengine-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gengine-client
.PHONY : gengine-client

# fast build rule for target.
gengine-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-client.dir/build.make CMakeFiles/gengine-client.dir/build
.PHONY : gengine-client/fast

#=============================================================================
# Target rules for targets named gengine-server

# Build rule for target.
gengine-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gengine-server
.PHONY : gengine-server

# fast build rule for target.
gengine-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-server.dir/build.make CMakeFiles/gengine-server.dir/build
.PHONY : gengine-server/fast

#=============================================================================
# Target rules for targets named unicode

# Build rule for target.
unicode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unicode
.PHONY : unicode

# fast build rule for target.
unicode/fast:
	$(MAKE) $(MAKESILENT) -f unicode/CMakeFiles/unicode.dir/build.make unicode/CMakeFiles/unicode.dir/build
.PHONY : unicode/fast

#=============================================================================
# Target rules for targets named unicode-test

# Build rule for target.
unicode-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unicode-test
.PHONY : unicode-test

# fast build rule for target.
unicode-test/fast:
	$(MAKE) $(MAKESILENT) -f unicode/CMakeFiles/unicode-test.dir/build.make unicode/CMakeFiles/unicode-test.dir/build
.PHONY : unicode-test/fast

src/array_list.o: src/array_list.c.o
.PHONY : src/array_list.o

# target to build an object file
src/array_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/array_list.dir/build.make CMakeFiles/array_list.dir/src/array_list.c.o
.PHONY : src/array_list.c.o

src/array_list.i: src/array_list.c.i
.PHONY : src/array_list.i

# target to preprocess a source file
src/array_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/array_list.dir/build.make CMakeFiles/array_list.dir/src/array_list.c.i
.PHONY : src/array_list.c.i

src/array_list.s: src/array_list.c.s
.PHONY : src/array_list.s

# target to generate assembly for a file
src/array_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/array_list.dir/build.make CMakeFiles/array_list.dir/src/array_list.c.s
.PHONY : src/array_list.c.s

src/client.o: src/client.c.o
.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-client.dir/build.make CMakeFiles/c-client.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-client.dir/build.make CMakeFiles/c-client.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-client.dir/build.make CMakeFiles/c-client.dir/src/client.c.s
.PHONY : src/client.c.s

src/game_client.o: src/game_client.cpp.o
.PHONY : src/game_client.o

# target to build an object file
src/game_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-client.dir/build.make CMakeFiles/gengine-client.dir/src/game_client.cpp.o
.PHONY : src/game_client.cpp.o

src/game_client.i: src/game_client.cpp.i
.PHONY : src/game_client.i

# target to preprocess a source file
src/game_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-client.dir/build.make CMakeFiles/gengine-client.dir/src/game_client.cpp.i
.PHONY : src/game_client.cpp.i

src/game_client.s: src/game_client.cpp.s
.PHONY : src/game_client.s

# target to generate assembly for a file
src/game_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-client.dir/build.make CMakeFiles/gengine-client.dir/src/game_client.cpp.s
.PHONY : src/game_client.cpp.s

src/server.o: src/server.c.o
.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-server.dir/build.make CMakeFiles/c-server.dir/src/server.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-server.dir/build.make CMakeFiles/gengine-server.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-server.dir/build.make CMakeFiles/c-server.dir/src/server.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-server.dir/build.make CMakeFiles/gengine-server.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c-server.dir/build.make CMakeFiles/c-server.dir/src/server.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gengine-server.dir/build.make CMakeFiles/gengine-server.dir/src/server.c.s
.PHONY : src/server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... array_list"
	@echo "... c-client"
	@echo "... c-server"
	@echo "... gengine-client"
	@echo "... gengine-server"
	@echo "... unicode"
	@echo "... unicode-test"
	@echo "... src/array_list.o"
	@echo "... src/array_list.i"
	@echo "... src/array_list.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/game_client.o"
	@echo "... src/game_client.i"
	@echo "... src/game_client.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

